/**
 * Writes supabase/seed.sql from a menu JSON file in the week-1 shape (lib/types.ts MenuData, whole naira).
 *
 *   node scripts/build-seed.mts                       # data/menu.json as "yakoyo"
 *   node scripts/build-seed.mts <menu.json> <slug> <order prefix> [logo url]
 *
 * Row ids are UUIDv5 of "<slug>/<table>/<json id>", so the output is stable between runs, and every
 * insert is `on conflict do nothing`, so applying the seed again never overwrites an owner's edits.
 * The restaurant has no owner until one is assigned (see README).
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import type { MenuData } from '../lib/types';

const [file = 'data/menu.json', slug = 'yakoyo', orderPrefix = 'YK', logoUrl = '/brand/logo.png'] =
  process.argv.slice(2);
const OUTPUT = 'supabase/seed.sql';

const menu: MenuData = JSON.parse(readFileSync(file, 'utf8'));

// Fixed namespace for this app's seed ids.
const NAMESPACE = Buffer.from('b7e6a1d23c4f4e5a9b8c7d6e5f4a3b2c', 'hex');

function uuidv5(name: string): string {
  const hash = createHash('sha1').update(NAMESPACE).update(name).digest();
  hash[6] = (hash[6] & 0x0f) | 0x50;
  hash[8] = (hash[8] & 0x3f) | 0x80;
  const hex = hash.subarray(0, 16).toString('hex');
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
}

const id = (table: string, jsonId: string) => uuidv5(`${slug}/${table}/${jsonId}`);
const kobo = (naira: number) => naira * 100;

type Value = string | number | boolean | null | { json: unknown } | { ints: number[] };

function literal(value: Value): string {
  if (value === null) return 'null';
  if (typeof value === 'number') {
    if (!Number.isInteger(value)) throw new Error(`Expected an integer, got ${value}`);
    return String(value);
  }
  if (typeof value === 'boolean') return String(value);
  if (typeof value === 'string') return `'${value.replace(/'/g, "''")}'`;
  if ('ints' in value) return `'{${value.ints.join(',')}}'::integer[]`;
  return `${literal(JSON.stringify(value.json))}::jsonb`;
}

function insert(table: string, rows: Record<string, Value>[]): string {
  if (rows.length === 0) return '';
  const columns = Object.keys(rows[0]);
  const values = rows.map((row) => `  (${columns.map((column) => literal(row[column])).join(', ')})`);
  return `insert into public.${table} (${columns.join(', ')}) values\n${values.join(',\n')}\non conflict do nothing;\n`;
}

const settings = menu.business_settings;
const restaurantId = id('restaurants', settings.id);

const packagingKobo = Object.fromEntries(
  Object.entries(settings.packaging).map(([key, naira]) => [key, naira === null ? null : kobo(naira)]),
);

const sql = [
  `-- Generated by scripts/build-seed.mts from ${file}. Do not edit by hand; re-run the script.\n`,
  insert('restaurants', [
    {
      id: restaurantId,
      slug,
      name: settings.name,
      whatsapp_number: `+${settings.whatsapp_number.replace(/\D/g, '')}`,
      address: settings.address,
      maps_url: settings.maps_url,
      opening_hours: { json: settings.opening_hours },
      delivery_hours: { json: settings.delivery_hours },
      accepts_pickup: settings.accepts_pickup,
      accepts_delivery: settings.accepts_delivery,
      delivery_fee_tiers_kobo: { ints: settings.delivery_fee_tiers.map(kobo) },
      packaging_kobo: { json: packagingKobo },
      accent_hex: settings.brand_color,
      logo_url: logoUrl,
      order_prefix: orderPrefix,
      is_open_override: settings.is_open_override,
      is_published: true,
    },
  ]),
  insert(
    'categories',
    menu.categories.map((category) => ({
      id: id('categories', category.id),
      restaurant_id: restaurantId,
      name: category.name,
      slug: category.slug,
      sort_order: category.sort_order,
      is_active: category.is_active,
    })),
  ),
  insert(
    'items',
    menu.menu_items.map((item) => ({
      id: id('items', item.id),
      restaurant_id: restaurantId,
      category_id: id('categories', item.category_id),
      name: item.name,
      description: item.description,
      price_kobo: kobo(item.price),
      photo_url: item.image_url,
      is_available: item.is_available,
      sort_order: item.sort_order,
      pos_name: item.pos_name,
    })),
  ),
  insert(
    'option_groups',
    menu.option_groups.map((group) => ({
      id: id('option_groups', group.id),
      restaurant_id: restaurantId,
      name: group.name,
      selection_type: group.selection_type,
      is_required: group.is_required,
      min_select: group.min_select,
      max_select: group.max_select,
      sort_order: group.sort_order,
    })),
  ),
  insert(
    'options',
    menu.options.map((option) => ({
      id: id('options', option.id),
      restaurant_id: restaurantId,
      option_group_id: id('option_groups', option.option_group_id),
      name: option.name,
      price_delta_kobo: kobo(option.price_delta),
      is_available: option.is_available,
      sort_order: option.sort_order,
      pos_name: option.pos_name,
    })),
  ),
  insert(
    'item_option_groups',
    menu.menu_item_option_groups.map((link) => ({
      restaurant_id: restaurantId,
      item_id: id('items', link.menu_item_id),
      option_group_id: id('option_groups', link.option_group_id),
    })),
  ),
].join('\n');

writeFileSync(OUTPUT, sql);
console.log(
  `Wrote ${OUTPUT}: ${settings.name} (/r/${slug}), ${menu.categories.length} categories, ` +
    `${menu.menu_items.length} items, ${menu.option_groups.length} option groups, ${menu.options.length} options`,
);
